"""Add training_center to Club model

Revision ID: 04469e08b1f0
Revises: fee5e428852d
Create Date: 2025-10-30 18:26:46.859051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04469e08b1f0'
down_revision: Union[str, Sequence[str], None] = 'fee5e428852d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('training_center', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'training_center')
    # ### end Alembic commands ###
