"""Update player column names to snake_case

Revision ID: 4c8251fcc2b2
Revises: f9a9fa2cacde
Create Date: 2025-12-26 21:10:04.979816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c8251fcc2b2'
down_revision: Union[str, Sequence[str], None] = 'f9a9fa2cacde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('substitutions', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('tackles', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('chances_created', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('saves', sa.Integer(), nullable=True))
    op.add_column('players', sa.Column('clean_sheets', sa.Integer(), nullable=True))
    op.drop_column('players', 'shots_on_goal')
    op.drop_column('players', 'substitute_appearances')
    op.drop_column('players', 'defenses')
    op.drop_column('players', 'shots')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('shots', sa.INTEGER(), nullable=True))
    op.add_column('players', sa.Column('defenses', sa.INTEGER(), nullable=True))
    op.add_column('players', sa.Column('substitute_appearances', sa.INTEGER(), nullable=True))
    op.add_column('players', sa.Column('shots_on_goal', sa.INTEGER(), nullable=True))
    op.drop_column('players', 'clean_sheets')
    op.drop_column('players', 'saves')
    op.drop_column('players', 'chances_created')
    op.drop_column('players', 'tackles')
    op.drop_column('players', 'substitutions')
    # ### end Alembic commands ###
