"""Auto migration 20260104_194311

Revision ID: 5143a36867a1
Revises: ad30cefd782b
Create Date: 2026-01-04 19:43:12.606538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5143a36867a1'
down_revision: Union[str, Sequence[str], None] = 'ad30cefd782b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('field_players', sa.Column('body_fat', sa.Float(), nullable=True))
    op.add_column('field_players', sa.Column('muscle_mass', sa.Float(), nullable=True))
    op.add_column('field_players', sa.Column('hdl', sa.Float(), nullable=True))
    op.add_column('field_players', sa.Column('ldl', sa.Float(), nullable=True))
    op.add_column('field_players', sa.Column('total_cholesterol', sa.Float(), nullable=True))
    op.add_column('field_players', sa.Column('triglycerides', sa.Float(), nullable=True))
    op.add_column('goalkeepers', sa.Column('body_fat', sa.Float(), nullable=True))
    op.add_column('goalkeepers', sa.Column('muscle_mass', sa.Float(), nullable=True))
    op.add_column('goalkeepers', sa.Column('hdl', sa.Float(), nullable=True))
    op.add_column('goalkeepers', sa.Column('ldl', sa.Float(), nullable=True))
    op.add_column('goalkeepers', sa.Column('total_cholesterol', sa.Float(), nullable=True))
    op.add_column('goalkeepers', sa.Column('triglycerides', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goalkeepers', 'triglycerides')
    op.drop_column('goalkeepers', 'total_cholesterol')
    op.drop_column('goalkeepers', 'ldl')
    op.drop_column('goalkeepers', 'hdl')
    op.drop_column('goalkeepers', 'muscle_mass')
    op.drop_column('goalkeepers', 'body_fat')
    op.drop_column('field_players', 'triglycerides')
    op.drop_column('field_players', 'total_cholesterol')
    op.drop_column('field_players', 'ldl')
    op.drop_column('field_players', 'hdl')
    op.drop_column('field_players', 'muscle_mass')
    op.drop_column('field_players', 'body_fat')
    # ### end Alembic commands ###
