"""Separate goalkeepers and field players - clean

Revision ID: 92e046593961
Revises: 4c8251fcc2b2
Create Date: 2025-12-28 13:52:44.179234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine import Inspector


# revision identifiers, used by Alembic.
revision: str = '92e046593961'
down_revision: Union[str, Sequence[str], None] = '4c8251fcc2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'players' in tables:
        # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('players')

    op.create_table('goalkeepers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True, default="Goleiro"),
    sa.Column('age', sa.Integer(), nullable=True, default=0),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True, default=0),
    sa.Column('substitutions', sa.Integer(), nullable=True, default=0),
    sa.Column('saves', sa.Integer(), nullable=True, default=0),
    sa.Column('goals_conceded', sa.Integer(), nullable=True, default=0),
    sa.Column('assists', sa.Integer(), nullable=True, default=0),
    sa.Column('fouls_committed', sa.Integer(), nullable=True, default=0),
    sa.Column('fouls_suffered', sa.Integer(), nullable=True, default=0),
    sa.Column('yellow_cards', sa.Integer(), nullable=True, default=0),
    sa.Column('red_cards', sa.Integer(), nullable=True, default=0),
    sa.Column('club_id', sa.Integer(), sa.ForeignKey('clubs.id'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goalkeepers_id'), 'goalkeepers', ['id'], unique=False)
    op.create_index(op.f('ix_goalkeepers_name'), 'goalkeepers', ['name'], unique=False)

    op.create_table('field_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True, default=0),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True, default=0),
    sa.Column('substitutions', sa.Integer(), nullable=True, default=0),
    sa.Column('goals', sa.Integer(), nullable=True, default=0),
    sa.Column('assists', sa.Integer(), nullable=True, default=0),
    sa.Column('total_shots', sa.Integer(), nullable=True, default=0),
    sa.Column('shots_on_goal', sa.Integer(), nullable=True, default=0),
    sa.Column('fouls_committed', sa.Integer(), nullable=True, default=0),
    sa.Column('fouls_suffered', sa.Integer(), nullable=True, default=0),
    sa.Column('yellow_cards', sa.Integer(), nullable=True, default=0),
    sa.Column('red_cards', sa.Integer(), nullable=True, default=0),
    sa.Column('club_id', sa.Integer(), sa.ForeignKey('clubs.id'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_players_id'), 'field_players', ['id'], unique=False)
    op.create_index(op.f('ix_field_players_name'), 'field_players', ['name'], unique=False)
    op.create_index(op.f('ix_field_players_position'), 'field_players', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_field_players_position'), table_name='field_players')
    op.drop_index(op.f('ix_field_players_name'), table_name='field_players')
    op.drop_index(op.f('ix_field_players_id'), table_name='field_players')
    op.drop_table('field_players')
    op.drop_index(op.f('ix_goalkeepers_name'), table_name='goalkeepers')
    op.drop_index(op.f('ix_goalkeepers_id'), table_name='goalkeepers')
    op.drop_table('goalkeepers')

    op.create_table('players',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('jersey_number', sa.INTEGER(), nullable=True),
    sa.Column('position', sa.VARCHAR(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('height', sa.FLOAT(), nullable=True),
    sa.Column('weight', sa.FLOAT(), nullable=True),
    sa.Column('nationality', sa.VARCHAR(), nullable=True),
    sa.Column('games', sa.INTEGER(), nullable=True),
    sa.Column('substitutions', sa.INTEGER(), nullable=True),
    sa.Column('goals', sa.INTEGER(), nullable=True),
    sa.Column('assists', sa.INTEGER(), nullable=True),
    sa.Column('tackles', sa.INTEGER(), nullable=True),
    sa.Column('chances_created', sa.INTEGER(), nullable=True),
    sa.Column('fouls_committed', sa.INTEGER(), nullable=True),
    sa.Column('fouls_suffered', sa.INTEGER(), nullable=True),
    sa.Column('yellow_cards', sa.INTEGER(), nullable=True),
    sa.Column('red_cards', sa.INTEGER(), nullable=True),
    sa.Column('saves', sa.INTEGER(), nullable=True),
    sa.Column('goals_conceded', sa.INTEGER(), nullable=True),
    sa.Column('clean_sheets', sa.INTEGER(), nullable=True),
    sa.Column('club_id', sa.INTEGER(), sa.ForeignKey('clubs.id'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_position'), 'players', ['position'], unique=False)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_index(op.f('ix_players_id'), 'players', ['id'], unique=False)
    # ### end Alembic commands ###
