"""Auto migration 20260104_194434

Revision ID: 964f01f9ce4d
Revises: 5143a36867a1
Create Date: 2026-01-04 19:44:35.014009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '964f01f9ce4d'
down_revision: Union[str, Sequence[str], None] = '5143a36867a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
