"""Add jersey_number to Player model

Revision ID: a067d48b9da1
Revises: 11b15db81b43
Create Date: 2025-10-28 15:44:24.855798

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a067d48b9da1'
down_revision: Union[str, Sequence[str], None] = '11b15db81b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('jersey_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'jersey_number')
    # ### end Alembic commands ###
