"""Add age column to FieldPlayer and Goalkeeper

Revision ID: ad30cefd782b
Revises: 89e23ee372e3
Create Date: 2025-12-30 22:17:12.084331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad30cefd782b'
down_revision: Union[str, Sequence[str], None] = '89e23ee372e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
