"""Update player stats columns

Revision ID: f9a9fa2cacde
Revises: 04469e08b1f0
Create Date: 2025-11-18 05:00:01.457145

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'f9a9fa2cacde'
down_revision: Union[str, Sequence[str], None] = '04469e08b1f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
