"""Remove training_center column from Club

Revision ID: fee5e428852d
Revises: a067d48b9da1
Create Date: 2025-10-29 19:53:52.117328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee5e428852d'
down_revision: Union[str, Sequence[str], None] = 'a067d48b9da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'training_center')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('training_center', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
